In [3]:
import numpy as np

v1 = np.array([1, 2, 3]) #A 3-dimensional vector; and don't forget paranthesis
v2 = np.array([4, 5, 6])

print(v1)
print(v2)


[1 2 3]
[4 5 6]


In [5]:
v_add = v1 + v2
v_sub = v1 - v2
print("v1 + v2:", v_add)
print("v1 - v2:", v_sub)


v1 + v2: [5 7 9]
v1 - v2: [-3 -3 -3]


In [6]:
scalar = 2
v_scaled = scalar*v1

print(v_scaled)

[2 4 6]


In [7]:
dot_product = np.dot(v1, v2)

print(dot_product)

32


In [8]:
magnitude_v1 = np.linalg.norm(v1)

print(magnitude_v1)

3.7416573867739413


In [10]:
# Creating a 2x3 matrix
A = np.array([[1, 2, 3], [4, 5, 6]]) # don't forget double bracket
print("Matrix A:\n", A)

# Creating a 3x3 matrix
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print("Matrix B:\n", B)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [12]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print("A + C =\n", matrix_add)
print("A - C =\n", matrix_sub)

A + C =
 [[ 2  4  6]
 [ 8 10 12]]
A - C =
 [[0 0 0]
 [0 0 0]]


In [14]:
matrix_mult = np.dot(A, B)
print("A * B:/n", matrix_mult)

A * B:/n [[ 66  72  78]
 [156 171 186]]


In [15]:
transpose_A = A.T
print("Transpose of A:\n", transpose_A)


Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]


In [16]:
A = np.array([[2, 3], [4, -1]])
b = np.array ([5, 3])
print(A)
print(b)
x = np.linalg.solve(A, b)
print(x)

[[ 2  3]
 [ 4 -1]]
[5 3]
[1. 1.]


In [18]:
A = np.array([[2, 1],[1, 2]])
e_value, e_vectors = np.linalg.eig(A)

print("eigenvalue: \n:", e_value)
print("eigenvectors:\n", e_vectors)


eigenvalue: 
: [3. 1.]
eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [20]:

A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print(A)
print("Inverse of A:\n", A_inv)

[[4 7]
 [2 6]]
Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [21]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [22]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
