I will import the same code from powerpoints and homework for functions.

In [6]:
import numpy as np
import time
import matplotlib.pyplot as plt

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations


def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations




A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

tol = 1e-9
x0 = np.zeros_like(b)
maxIterations = 10000


In [2]:
print(jacobi(A, b, x0, tol, maxIterations))

(array([1., 1., 1., 1., 1.]), 5111)


In [3]:
print(gauss_seidel(A, b, x0, tol, maxIterations))

(array([1., 1., 1., 1., 1.]), 29)


In [4]:
#Use your Jacobi and Gauss-Seidel functions to solve:

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])

maxIterations = 1000000
print(jacobi(A, b, x0, tol, maxIterations))
print(gauss_seidel(A, b, x0, tol, maxIterations))

(array([1., 0., 0., 0., 0.]), 414487)
(array([1., 0., 0., 0., 0.]), 1)


In [5]:
#Use you Jacobi and Gauss-Seidel functions to solve:

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])

maxIterations = 1000000
print(jacobi(A, b, x0, tol, maxIterations))
print(gauss_seidel(A, b, x0, tol, maxIterations))

(array([9.99932692e-10, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00]), 414486)
(array([9.99901114e-06, 9.99990002e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00]), 115136)
