In [4]:
import numpy as np

def diagDom (A):
    diagElements = []
    n = len(A)
    for i in range(n):
        rowSum = 0
        rowSum = sum(abs(A[i][j]) for j in range(n) if j != i) #I used inspiration from the Jacobian/Gauss Functions
        if abs(A[i][i]) < rowSum:
            print(A)
            return False
    print(A)
    return True
        
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

diagDom(A)
        

[[1 2 3]
 [4 5 6]
 [7 8 9]]


False